# Set language for the project
language: cpp

# Package dependencies
addons:
  apt:
    packages:
      - bison
      - qttools5-dev-tools
      - libqt5gui5
      - libqt5widgets5
      - libqt5opengl5-dev
      - qtbase5-dev
      - qt5-default
      - libfreetype6-dev
      - libftgl-dev
      - pkg-config
      - libtool
      - automake

# Main build matrix
matrix:
  include:
    - os: linux
      dist: xenial
      compiler: g++

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.12.3-xenial -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -q; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install qt512base -y; fi

# Build Stages
jobs:
  include:
    - stage: Build
      name: Serial (CLI, GUI)
      script: 
        - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./ci/ubuntu.build.serial.gui; fi
        - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./autogen.sh && ./configure --with-gui && make; fi
    - script:
        - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./ci/ubuntu.build.parallel; fi
        - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./autogen.sh && ./configure --with-gui && make; fi
      name: Parallel (CLI)
    - stage: System Tests
      script: echo "Hello!"
