# Set language for the project
language: cpp

# Package dependencies
addons:
  apt:
    packages:
      - bison
      - qttools5-dev-tools
      - libqt5gui5
      - libqt5widgets5
      - libqt5opengl5-dev
      - qtbase5-dev
      - qt5-default
      - libfreetype6-dev
      - libftgl-dev
      - pkg-config
      - libtool
      - automake
  homebrew:
    packages:
      - qt5
      - bison

# Build matrix
os:
  - linux
#  - osx
env:
  - PARALLEL=false
  - PARALLEL=true

# UBUNTU: Add PPA repo for updated Qt libs (serial build only)
before_install:
  - if [[ "$TRAVIS_OS_NAME" = "linux" && "$PARALLEL" = "false" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y; fi
  - if [[ "$TRAVIS_OS_NAME" = "linux" && "$PARALLEL" = "false" ]]; then sudo apt-get update -q; fi
  - if [[ "$TRAVIS_OS_NAME" = "linux" && "$PARALLEL" = "false" ]]; then sudo apt-get install qt510base -y; fi

# Build Stages
jobs:
  include:
    - stage: Serial Build
      env: PARALLEL=false
      script:
        - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./ci/ubuntu.build.serial.gui; fi
          if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./ci/osx.build.serial.gui; fi
    - stage: Parallel Build
      env: PARALLEL=true
      script:
        - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./ci/ubuntu.build.parallel; fi
          if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./ci/osx.build.parallel; fi
    - stage: System Tests
      script: echo "Hello!"
