# Set language for the project
language: cpp

# Package dependencies
addons:
  apt:
    packages:
      - bison
      - libfreetype6-dev
      - libftgl-dev
      - pkg-config
      - libtool
      - automake
  homebrew:
    packages:
      - qt5
      - bison

# UBUNTU: Add PPA repo for updated Qt libs (serial build only)
before_install:
  - if [[ "$TRAVIS_OS_NAME" = "linux" && "$PARALLEL" = "false" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y; fi
  - if [[ "$TRAVIS_OS_NAME" = "linux" && "$PARALLEL" = "false" ]]; then sudo apt-get update -q; fi
  - if [[ "$TRAVIS_OS_NAME" = "linux" && "$PARALLEL" = "false" ]]; then sudo apt-get install qt510base -y; fi

# Build Stages
jobs:
  include:
    - stage: Build
      name: Linux (Serial, GUI)
      env: PARALLEL=false
      os: linux
      script: ./ci/ubuntu.trusty/ubuntu.build.serial.gui
    - stage: Build
      name: Linux (Parallel)
      env: PARALLEL=true
      os: linux
      script: ./ci/ubuntu.trusty/ubuntu.build.parallel
    - stage: Build
      name: OSX (Serial, GUI)
      env: PARALLEL=false
      os: osx
      script: ./ci/osx.highsierra/osx.build.serial.gui
    - stage: Build
      name: OSx (Parallel)
      env: PARALLEL=true
      os: osx
      script: ./ci/osx.highsierra/osx.build.parallel
    - stage: System Tests
      script: echo "Hello!"
