# Set language for the project
language: cpp

# Package dependencies
addons:
  apt:
    packages:
      - bison
      - libfreetype6-dev
      - libftgl-dev
      - pkg-config
      - libtool
      - automake
      - libopenmpi-dev
      - openmpi
  homebrew:
    packages:
      - qt5
      - bison

# UBUNTU: Add PPA repo for updated Qt libs (serial build only)
before_install:
  - if [[ "$TRAVIS_OS_NAME" = "linux" && "$PARALLEL" = "false" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y; fi
  - if [[ "$TRAVIS_OS_NAME" = "linux" && "$PARALLEL" = "false" ]]; then sudo apt-get update -q; fi
  - if [[ "$TRAVIS_OS_NAME" = "linux" && "$PARALLEL" = "false" ]]; then sudo apt-get install qt510base -y; fi

# Build Stages
jobs:
  include:
    - stage: Build Stage A
      name: Linux (Serial, GUI)
      env: PARALLEL=false
      os: linux
      cache:
        directories:
          - artifacts
      script: ./ci/ubuntu.trusty/ubuntu.build.serial.gui
    - stage: Build Stage B
      name: Linux (Parallel)
      env: PARALLEL=true
      os: linux
      cache:
        directories:
          - artifacts
      script: ./ci/ubuntu.trusty/ubuntu.build.parallel
    - stage: System Tests
      name: Serial
      env: PARALLEL=false
      os: linux
      cache:
        directories:
          - artifacts
      script: ./ci/ubuntu.trusty/ubuntu.test.serial
    - stage: Build Stage B
      name: OSX (Serial, GUI)
      env: PARALLEL=false
      os: osx
      script: ./ci/osx.highsierra/osx.build.serial.gui
    - stage: Build Stage B
      name: OSX (Parallel)
      env: PARALLEL=true
      os: osx
      script: ./ci/osx.highsierra/osx.build.parallel

# Build Stage Order
stages:
  - Build Stage A
  - System Tests (Serial)
  - System Tests (Parallel)
  - Build Stage B
