name: AppImage (GUI/Serial) (Ubuntu 18.04)

on:
  push:
    branches:
    - develop
    - release/*

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisties
      run: |
        # Development Packages
        sudo apt-get install bison libfreetype6-dev libftgl-dev ninja-build
        # Qt 5.13.2
        sudo add-apt-repository ppa:beineri/opt-qt-5.13.2-bionic -y
        sudo apt-get update -q
        sudo apt-get install qt513base -y
    - name: Build (CMake/Ninja)
      run: |
        mkdir build
        cd build
        cmake -G "Ninja" -DGUI:bool=true ../
        ninja
        cd ../
    - name: Create AppImage
      run: |
        # Obtain appimage build script
        wget -q https://raw.githubusercontent.com/trisyoungs/scripts/master/build-appimage.sh -O build-appimage.sh
        chmod u+x build-appimage.sh
        # Determine current code version
        VERSION=`grep "DISSOLVEVERSION" src/version.h | sed "s/.*\"\(.*\)\"/\1/g"`
        # Build images
        ./build-appimage.sh -a Dissolve-Serial -v ${VERSION} -b ${SERIALBINARY}
        ./build-appimage.sh -a Dissolve-GUI -v ${VERSION} -b ${GUIBINARY}
