name: DIssolve Serial / GUI (AppImage) (Ubuntu 18.04)

on:
  push:
    branches:
    - develop
    - release/*

jobs:
  build:

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Prep (Ubuntu / Qt5)
      if: matrix.os == 'ubuntu-18.04'
      run: |
        sudo add-apt-repository ppa:beineri/opt-qt-5.13.1-bionic -y
        sudo apt-get update -q
        sudo apt-get install qt513base -y
    - name: Build (CMake/Ninja)
      run: |
        mkdir build
        cd build
        cmake -G "Ninja" -DGUI:bool=true ../
        ninja
        cd ../
