name: Win64 (GUI/Serial) (Windows Server Latest)

on:
  push:
    branches:
    - develop
    - release/*

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisties
      run: |
        $Wc = New-Object System.Net.WebClient
        $Wc.DownloadFile('http://download.qt.io/archive/qt/5.13/5.13.1/qt-opensource-windows-x86-5.13.1.exe', 'qt.exe')
        $Wc.Dispose()
        echo 'Downloaded qt-opensource-windows-x86-5.13.1.exe'
        $env:QT_INSTALL_DIR = 'C:/Qt'
        Start-Process qt.exe -ArgumentList '--verbose --script ci/windows/qtifwsilent.qs' -NoNewWindow -Wait
        Remove-Item qt.exe
        $env:QTDIR = "C:/Qt/5.13.1/mingw73_64"
        $env:PATH += "C:/Qt/Tools/mingw730_64/bin;"
        $env:PATH += "C:/Qt/5.13.1/mingw73_64/bin;"
        choco install -y zip --version 3.0
        choco install -y ninja
        choco install -y winflexbison
        choco install -y innounp
        choco install -y wget
    - name: Build Freetype
      run: |
        choco uninstall -y strawberryperl
        cd $HOME
        wget 'https://download.savannah.gnu.org/releases/freetype/ft2101.zip' -O 'ft.zip'
        unzip ./ft.zip
        Echo 'Compiling FreeType...'
        mkdir freetype-build
        cd freetype-build
        cmake -G "Ninja" ../freetype-2.10.1 -DFT_WITH_ZLIB=OFF -DFT_WITH_PNG=OFF -DFT_WITH_HARFBUZZ=OFF -DFT_WITH_BZip2=OFF
        ninja
    - name: Build FTGL
      run: |
        cd $HOME
        echo 'Compiling FTGL'
        git clone 'https://github.com/frankheckenbach/ftgl.git' ftgl-latest
        mkdir ftgl-build
        cd ftgl-build
        $env:INCLUDE += "$HOME\\freetype-2.10.1;"
        $env:LIB += "$HOME\\freetype-build;"
        cmake -G "Ninja" ..\ftgl-latest
        ninja
    - name: Build (CMake/Ninja)
      run: |
        mkdir build
        cd build
        $env:QTDIR = "C:/Qt/5.13.1/mingw73_64"
        $env:PATH += "C:/Qt/Tools/mingw730_64/bin;"
        $env:PATH += "C:/Qt/5.13.1/mingw73_64/bin;"
        $env:INCLUDE += "$HOME\\freetype-2.10.1;"
        $env:LIB += "$HOME\\freetype-build;"
        $env:INCLUDE += "$HOME\\ftgl-latest\\src;"
        $env:LIB += "$HOME\\ftgl-build\\src;"
        cmake -G "Ninja" -DGUI:bool=true ../
        ninja
        cd ../
    - name: Create Installer
      run: |
